[package]
name = "dropbox-content-hash"
version = "0.1.0"
authors = ["Bill Fraser <wfraser@codewise.org>"]
edition = "2021"

[dependencies]
clap = { version = "3", features = ["cargo", "derive"] }
parallel_reader = "0.1.2"
ring = "0.16"
