[package]
name = "dropbox-content-hash"
version = "0.1.1"
authors = ["Bill Fraser <wfraser@codewise.org>"]
edition = "2021"

[dependencies]
clap = { version = "4", features = ["cargo", "derive", "string"] }
parallel_reader = "0.1.2"
ring = ">=0.17.14"
